package com.sjchoi.weather.dataclass

data class weatherUVIndex(
    val resultCode : Int,
    val resultMsg : String,
    val numOfRows : Int,
    val pageNo : Int,
    val totalCount : Int,
    val dataType : String,
    val code : String,
    val areaNo : Int,
    val date : Int,
    val today : Int,
    val tomorrow : Int,
    val dayaftertomorrow : Int,
    val twodaysaftertomorrow : Int
)

data class atmospherIndex(
    val numOfRows : Int,
    val pageNo : Int,
    val totalCount :Int,
    val resultCode : Int,
    val resultMsg : String,
    val dataType : String,
    val code : String,
    val areaNo : Int,
    val	date : Int,
    val h3 : Int,
    val h6 : Int,
    val h9 : Int,
    val h12 : Int,
    val h15 : Int,
    val h18 : Int,
    val h21 : Int,
    val h24 : Int,
    val h27 : Int,
    val h30 : Int,
    val h33 : Int,
    val h36 : Int,
    val h39 : Int,
    val h42 : Int,
    val h45 : Int,
    val h48 : Int,
    val h51 : Int,
    val h54 : Int,
    val h57 : Int,
    val h60 : Int,
    val h63 : Int,
    val h66 : Int,
    val h69 : Int,
    val h72 : Int,
    val h75 : Int,
    val h78 : Int
)
